---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-login-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCV2uYUXQPWJ5bXo024HMENoRcdtc8LDW8rLByEF4teB/ch0bmEnvoHuhuzswMJ/GUsCq1CXhzBbRXTpdAJBN5BcFcCtyrFQ7f4ZzFTmB6nJiDWtUIzrrAEQflOx3itMZdQOHYA0qVyPQq/D/6AZd9WVZ/z2pOXBiRCxr1jr0Aya5xAoLJ26tYRN9eWn+XC4IqVv4spnqtG9WVeaHlWVsk4rprLEjkCpQjMiJVlnf8OOyyiCTiMsaWjJN9ZiN0JcUdPDoHH7jWF830opvhqqz0Vrvx6VCXc78PcLA/tsEYBSlV+mU5pL/W5MbR8s4ZOyoibCmtbf8nYRLNN1cthwCQ9ToPvoPHzPLm9tAjb04yTNDKnCtMa8RsUic1jGeURzgJL0L8aCJxPARBTD5vcgKGnCgOMUJolEhjzDCumtNTT0mJGmmDfS1p3ZLE0BapzCHyBTokVw9tD4ghgDSmYtcr91ZQlKn3Lu3DLjG+hEAiU7odsRpnkIjfZWav9YgnyugLprJ9oF86PC/dtcwHWSg/YXMHVcJTlAyGvAO7VEYloR5xc2og6vpgS77tfB10zMv6fCoPG8UpZrqd+8FKux4o049E36E4zBUe8FdJUgRkLBNorhVKcJTaZ9Hqq7OW9pC0fcYHjs9qHxigh4XNquoPvHuTG97tr8/OXrYvGXSSVjsNt7lhUvUZPUH34358D30uUuQMWRZE8G2hHLk4bjhmjIov/kS5so+Hhqd/J04S1lNjm6aMqBnhcmdLiN0oCxaSwh6O29RrhO8Bhc9ZYyS1rGCnYrpHdKKj9UTkcpFSmUPT+APkwOD2R3OCgdwdSBcjiYwQjJFRTTSbH4cRhEr17mzL7f/lPUHXubwLhwODL8dTGHpElzqfYCv4yW3/Zxj9t4u3Jo+RxHIkNMdSkzLj4p+1po1GYU+d3IiN0AvK8MFQqNtC40yy1H09KhISZa4+0n1qvNMdGeFw2qmQGO2qHJOqJnMxNHZRNOeICgYA=
  template:
    metadata:
      name: ghcr-login-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
