---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garage-app-creds
  namespace: default
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCts1S8DYvjt7tZKbMfWqlJBV0WMCPxuOrKUY3CO5Y9A4BD891qQMd0lRBwsWCPkJqI+1gt4JVX7jAj1uM1kUGGKmyXbMMCF9cMOD8f2ZgwP/7tD9k3vAfKSaUypvhqW0+FbgHpB5SQ555JZConD5OqtsWGchyW/f8Wa8Q3UNqRCp7K7NI6Cupe8muNaKlm9axq7oW1a74+jkKl3CJmLTG1UuqU8lzBlmdXvQUsMxA4qzkhgqc9d0FOMce2yB5QriFgLmP/lDoh7a3LU91cCAbVqirJlDlArJ1xj6lWmWiIfLyFRxlnGMZPIM0S7DSseUapgLw8poOLmqfr5yqAZzcEM9oCERyPpjDg8WkqoSA783B4LFbd65ptdW27H6Otb0Bk6ikSSmiVxeoRyRWZbLwDJdPupRCWqokywNl3OUbWWRUKB9qSdqdr4+CYXcxzODA5FZT3f6sxhCn5g6QWF8gJ3a7LNk5uLOAcOJgEk+Z+wpe5qnQCHniLDyVr+GaWd0OuMl5JvyZSvMmrBRbidakcsa4k/9hO8twq46cIbxZ36TVg5Vx3DE3bUn930JanB8bfcUfIdDPHO3ATYII4ZjpbZysIbl+BNYCW/ukMFcuAO8eB+sBDk1gwaSpiByIlasIHJU9427Kd+O0cp27U7KVf5tCgQmRPtT/ZxJ76BOLgsqQWSA//8HQCYzrMZwCwsEVXSANhhrJ6ItRNoVDCDsDuds3rXNoHB4R/Gw==
    ACCESS_SECRET_KEY: AgAXy9f8WPwjCM3EmYaUi+IrYS0L5qIhoH4buwhdhN9DinxwsF6WJXy4xQlzAcwqsEw0X6ol+RfxB8aPbOknRMAMg3R8Av9Y5cyqd0Cj8tdE/OC5z3DbqTqHb6NJoofujxjFkcelWnEM/mj8fSR/Sf/cI1Y1AbV3BeuA4jX1bM8BtkZz7G1hhpz8axkYnLaCvNUARk/jb2qOGXNS/s5aSKJIxvvj8wo/K85oNCPWgA0ieawCODsvZT6Hc/6MD5RtGYmoq8qS68NA128lKgAue35y1ViCVZlEbKOfHVhh3c64FkHzn6nMHVzA+FM6iJu6/pRP6Hc8DmGUwvPpn0xsa659fozf1HR02Af05xAUFAgagGFAcjji0PildnAGbQUPfXnUVXpAP38NLbmfva7BjtcFmPSUNOmc/dkAkz91L+BLqhgWE+vr7AHq86L+4T3H9vNjUhvfOhRiOvfYJdmJnXOo8iIpsflnoYpVDrJwtyJcf1ctiQgEkN41IrNFpbycHsz8hup8Tk/XkwrDxGGB+9zEeHotOkKdzBPk9a0nQnLyCpegeeA/8gbEtOOQxheFScxy/Cvg+vdxd1mcVbOvWPEQh/5sXVsI1+xFqWyhgFeld9yGnoIngNH8b2Rrlo81J3ZiuYddtGfk6OqVfBHXkO1Bxa67RnLws6+Bh8Btdis45I9zeCNkPRWDB/c5nZyWDgXLvcqVXO9mNM6Vpp/2cutvzXQR0UpI2UW4gwKs1mqb83JwJfAMsKAonHcBc4dj06TqC7vYK2eogwV4nQD2VMUw
  template:
    metadata:
      name: garage-app-creds
      namespace: default
