---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bot-maison-secret
  namespace: bot-maison
spec:
  encryptedData:
    token: AgBs8/AGH7cH/m8fcIqxOHOwz11R/w22Z0RztjUWYFQQKBQg7t1SBK1TXSfQqTcILoO1LloAl8d0EREwH0fk55JIkz7O16JI8oETGjYkJuio5IzYK5lcezgiPS/AKWIMRbt024UDFZNosYBCsw4W7lf3ndU5en6SZoKbEq6ulZ7ZlPMjipqcQNlluTzF2i63uCksRsqCUQ+mt91rMdjjTD/zEqV3coDfYheO5fk+yzlbOs3Ye4ukrzG1kaRsdPOTjWflzDBxZbiphzgtMzO11HoPfTa1wD6CGNxxG8N4u5qmfdwbRS6O/39gQC9c1dnmDtOtKl9N0G1u1nGdD0gli65RxLb15a95PaKhtJ/QX4evgGo55VpdSy2nWhwDyM/hYAn/MeGixY8WOH60CN4mtP1Nvk5PsUoDzjPCVw2+Hm3AybCBwDEtH84POo2cNHE4E+H6UbDR/R5fIZPi/g/7xF6DZYMXLgCm1552t8ogu6Xq5+OYVX85FKMgXicd3S4c7qpfNX8v0xpvt+Z9jfx6q4ZO05bJzkYoYzLTaJ/TCfuyiWEUOrtqzMU9wbAnl4MNZ73jgyEFZ/OrdbZzflNJVj3iWkHNnTRd28Pk8NseJRkX/heNdoANz81YoE48s2LV6tSkEsceZJ3yfTAUiTnvCo/hQZiqQuH0YQX/hQqzyyL44VoKpP0Re+Uq4LkZJj80v7M1/m0nnL9wahzuefZGgPYnW2oWlXaBD071eAO/K2P7dfMV/BtOlM7wNCF8g+FXSuBx0e/PZxrvvogsHV+R2KK0ulPtj9p5rrE=
  template:
    metadata:
      name: bot-maison-secret
      namespace: bot-maison
