apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-maison
  namespace: bot-maison
spec:
  selector:
    matchLabels:
      app: bot-maison
  template:
    metadata:
      labels:
        app: bot-maison
    spec:
      imagePullSecrets:
      - name: ghcr-login-secret
      containers:
      - name: bot-maison
        image: ghcr.io/arthurbr02/bot-maison:1.2.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-maison-secret
              key: token
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: bot-maison-db-app
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bot-maison-db-app
              key: password
        envFrom:
        - configMapRef:
            name: bot-maison-database-config
