apiVersion: apps/v1
kind: Deployment
metadata:
  name: ba-tb
  namespace: ba-tb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ba-tb
  template:
    metadata:
      labels:
        app: ba-tb
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: ba-tb
          image: ghcr.io/arthurbr02/ba-tb:1.0.2
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: ba-tb-config
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ba-tb-secret
                  key: DISCORD_TOKEN
            - name: MISTRAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ba-tb-secret
                  key: MISTRAL_API_KEY
            - name: SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: ba-tb-secret
                  key: SPOTIFY_CLIENT_ID
            - name: SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ba-tb-secret
                  key: SPOTIFY_CLIENT_SECRET
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ba-tb-db-app
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ba-tb-db-app
                  key: password